## Numpy Based Python Programs

In [ ]:
## Question:1 : https://www.hackerrank.com/challenges/np-arrays/problem

In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    rev = arr[::-1]
    
    res = numpy.array(rev,dtype=float)
    
    return res

arr = input().strip().split(' ')

result = arrays(arr)

print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [ ]:
## Question:2 : https://www.hackerrank.com/challenges/np-shape-reshape/problem

In [2]:
import numpy

Arr = list(map(int,input().split()))

Np = numpy.array(Arr).reshape((3,3))

print(Np)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
## Question:3 : https://www.hackerrank.com/challenges/np-transpose-and-flatten

In [3]:
import numpy as np

row,col = map(int,input().split())

Arr = []

for i in range(row):
    
    Arr.append(list(map(int,input().split())))

array = np.array(Arr)

# Transpose
print(np.transpose(array))

# Flatten
print(array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [ ]:
## Question:4 : https://www.hackerrank.com/challenges/np-concatenate/problem

In [4]:
import numpy as np

t = 2

Arr1 = []

Arr2 = []

N,M,P = map(int,input().split())


for i in range(N):
        
    Arr1.append(list(map(int,input().split())))

for i in range(M):
        
    Arr2.append(list(map(int,input().split())))

array_1 = np.array(Arr1)

array_2 = np.array(Arr2)

print(np.concatenate((array_1, array_2), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4 
3 4 
3 4 
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
## Question:5 : https://www.hackerrank.com/challenges/np-zeros-and-ones/problem

In [6]:
import numpy

N = tuple(map(int,input().strip().split()))

z = numpy.zeros(N, dtype=numpy.int)

o = numpy.ones(N, dtype=numpy.int)

print (z)
print('*'*10)
print (o)

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
**********
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [ ]:
## Question:6 : https://www.hackerrank.com/challenges/np-eye-and-identity/problem

In [13]:
import numpy as np

np.set_printoptions(legacy='1.13')

N,M = map(int,input().split())

print(np.eye(N,M,k=0))

4 5
[[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]


In [ ]:
## Question:7 : https://www.hackerrank.com/challenges/np-array-mathematics/problem

In [14]:
import numpy as np

n,m = map(int,input().split())

a=np.zeros((n,m),int)

b=np.zeros((n,m),int)

for i in range(n):
    
    a[i]=np.array(input().split(),int)

for i in range(n):
    
    b[i]=np.array(input().split(),int)  

print(a+b)

print(a-b)

print(a*b)

print(np.array(a/b,int))

print(a%b)

print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [ ]:
## Question:8 : https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem

In [15]:
import numpy as np

np.set_printoptions(legacy='1.13')

Arr = np.array(list(map(float,input().split())))

print(np.floor(Arr))

print(np.ceil(Arr))

print(np.rint(Arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
## Question:9 : https://www.hackerrank.com/challenges/np-sum-and-prod/problem

In [16]:
import numpy as np

N,M = map(int,input().split())

Arr = np.array([list(map(int,input().split())) for i in range(N)])

Sum = np.sum(Arr,axis = 0)

Product = np.prod(Sum , axis = None)

print(Product)

2 2
1 2
3 4
24


In [ ]:
## Question:10 : https://www.hackerrank.com/challenges/np-min-and-max/problem

In [17]:
import numpy as np

N,M = map(int,input().split())

Arr = np.array([list(map(int,input().split())) for i in range(N)])

Min = np.min(Arr,axis = 1)

print(np.max(Min,axis=None))

4 2
2 5
 3 7
 1 3
 4 0
3


In [ ]:
## Question:11 : https://www.hackerrank.com/challenges/np-mean-var-and-std/problem

In [18]:
import numpy as np

N,M = map(int,input().split())

Arr = np.array([list(map(int,input().split())) for i in range(N)])

Mean = np.mean(Arr,axis = 1)
print(Mean)

Var = np.var(Arr , axis = 0)
print(Var)

Std = round(np.std(Arr, axis = None),11)
print(Std)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [ ]:
## Question:12 : https://www.hackerrank.com/challenges/np-dot-and-cross/problem

In [19]:
import numpy as np

N = int(input())

Arr1 = np.array([list(map(int,input().split())) for i in range(N)])

Arr2 = np.array([list(map(int,input().split()))for i in range(N)])

print(np.dot(Arr1,Arr2))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [ ]:
## Question:13 : https://www.hackerrank.com/challenges/np-inner-and-outer/problem

In [20]:
import numpy as np

Arr1 = np.array(list(map(int,input().split())))

Arr2 = np.array(list(map(int,input().split())))

print(np.inner(Arr1,Arr2))

print(np.outer(Arr1,Arr2))

0 1
2 3
3
[[0 0]
 [2 3]]


In [ ]:
## Question:14 : https://www.hackerrank.com/challenges/np-polynomials/problem

In [21]:
import numpy as np

Arr = np.array(list(map(float,input().split())))

x = int(input())

print(np.polyval((Arr),x))

1.1 2 3
0
3.0


In [ ]:
## Question:15 : https://www.hackerrank.com/challenges/np-linear-algebra/problem

In [22]:
import numpy as np

N = int(input())

Arr = np.array([list(map(float,input().split())) for i in range(N)])

det = np.linalg.det(Arr)

print(round(det,2))

2
1.1 1.1 
1.1 1.1
0.0
